name: Build

on: [push, workflow_dispatch]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: chmod +x gradlew
    - name: Set up JDK 17
      uses: actions/setup-java@v4.5.0
      with:
        distribution: hotspot
        java-version: 17
    - name: Setup Android SDK
      uses: amyu/setup-android@v4
      with:
        build-tools-version: 30.0.1
        sdk-version: 26
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build mod jar
      run: ./gradlew deploy
    - name: Upload built jar file
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ${{ github.event.repository.name }}
        path: build/libs/${{ github.event.repository.name }}.jar
